name: ASP.NET Core Azure Devops Kubernetes DockerHub Video
on:
    push:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_HOOK_URL: ${{ secrets.SLACK_HOOK_URL }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      DISPLAY: ":99.0"
      CUCUMBER_TAGS: "(not @destinationspecific or @k8s) and (not @repositoryspecific or @dockerhub) and (not @applicationspecific or @aspnetcore) and (not @sourcespecific or @git)"
      DISABLE_HIGHLIGHTS: true
      DISABLE_SCREENSHOTS: true
      MOVE_TO_MOUSE_CURSOR: true
      MOUSE_VERTICAL_OFFSET: 74
      DISABLE_VIDEO: false
      STHREE_SCREENSHOT_ENABLED: true
      SCREENSHOT_BUCKET: octopus-guides-screenshots
      GIT_URL: https://github.com/OctopusSamples/RandomQuotes.git
      WISTIA_MEDIA_ID:
      VIDEO_FILE_NAME: aspnetcore-k8s-dockerhub.mp4
      SCREENSHOT_PATH: aspnetcore-app\k8s\dockerhub\git\
    steps:
      - uses: actions/checkout@v1
      - name: Install Puppet
        run: ./install.sh minikube.pp dockercreds.pp octopus.pp dotnetutilities.pp utilities.pp octopuscli.pp
        env:
          FACTER_dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          FACTER_dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Create Api Key
        run: ./scripts/create-apikey.sh
      - name: Create Worker
        run: sudo ./scripts/create-worker.sh
      - name: Create environments
        run: ./scripts/create-environments.sh
      - name: Create certificates
        run: ./scripts/create-certificates.sh
      - name: Create target
        run: ./scripts/create-k8starget.sh