name: ASP.NET Jenkins Octopus Built-in Feed Azure WebSites Screenshots
on: [push]
#on:
#  schedule:
#    - cron:  '0 3 * * *'
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - uses: azure/actions/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Create Web App
        shell: powershell
        run: |
          $exists = & az group exists --name jenkinsaspnetbuiltinfeed
          if ($exists -eq "false") {
            az group create --location australiaeast --name jenkinsaspnetbuiltinfeed --tags Lifetime=Permanent OwnerContact=@matthew.casperson
          }
          $plans = & az appservice plan list --resource-group jenkinsaspnetbuiltinfeed | ConvertFrom-Json
          if ($plans.Count -eq 0) {
            az appservice plan create --name jenkinsaspnetbuiltinfeed --resource-group jenkinsaspnetbuiltinfeed --number-of-workers 1 --sku F1
          }
          $apps = az webapp list --resource-group jenkinsaspnetbuiltinfeed | ConvertFrom-Json
          if ($apps.Count -eq 0) {
            az webapp create `
              -g jenkinsaspnetbuiltinfeed `
              -p jenkinsaspnetbuiltinfeed `
              -n jenkinsaspnetbuiltinfeed `
              --runtime "aspnet|V4.7"
          }
