name: ASP.NET Core TeamCity Octopus Built-in Feed Video
on:
#  push:
  schedule:
    - cron:  '0 19 9 * *'
jobs:
  build:
    runs-on: windows-2019
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      SLACK_HOOK_URL: ${{ secrets.SLACK_HOOK_URL }}
      MEDIA_PATH: C:\screenshots
      CUCUMBER_TAGS: "(not @destinationspecific or @iis) and (not @repositoryspecific or @octo-built-in-feed) and (not @applicationspecific or @aspnetcore)"
      WISTIA_MEDIA_ID: f925nu08uc
      DISABLE_HIGHLIGHTS: true
      DISABLE_SCREENSHOTS: true
      MOVE_TO_MOUSE_CUSROR: true
      MOUSE_VERTICAL_OFFSET: 74
      SCREENSHOT_BUCKET: octopus-guides-screenshots
      STHREE_SCREENSHOT_ENABLED: true
      GIT_URL: https://github.com/OctopusSamples/RandomQuotes.git
      NUGET_PATH:
      VIDEO_FILE_NAME: aspnetcore-teamcity-octopus-builtin-feed.mp4
      SCREENSHOT_PATH:
    steps:
    - uses: actions/checkout@v1
    - name: Disable Windows Defender
      shell: powershell
      run: reg add 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection' /v DisableRealtimeMonitoring /t REG_DWORD /d 1
    - name: Execute puppet
      shell: powershell
      run: ./install.ps1 -Scripts utilities.pp,dotnetutilities.pp,teamcity.pp,octopus.pp,iis.pp,sleep.pp,teamcitywait.pp
    - name: Create API key
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=$env:MOVE_TO_MOUSE_CUSROR"
        "-DmouseMoveVerticalOffset=$env:MOUSE_VERTICAL_OFFSET"
        "-DdisableHighlights=$env:DISABLE_HIGHLIGHTS"
        "-DdisableScreenshots=$env:DISABLE_SCREENSHOTS"
        "-DCucumberAlias-ExternalApiKeyFile=C:\api_key.txt"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        features\octopus\octopus-api-key.feature

    - name: Create API key for tests
      shell: powershell
      run: '& "C:\Program Files\Puppet Labs\Puppet\bin\puppet.bat" apply puppet\windows\octopus-api-key.pp --disable_warnings=deprecations'
    - name: Initial Team City Configuration
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=$env:MOVE_TO_MOUSE_CUSROR"
        "-DmouseMoveVerticalOffset=$env:MOUSE_VERTICAL_OFFSET"
        "-DdisableHighlights=$env:DISABLE_HIGHLIGHTS"
        "-DdisableScreenshots=$env:DISABLE_SCREENSHOTS"
        "-DnoProxyList=microsoft.com"
        "-DdumpAliasesOnFailure=true"
        "-DslackHookUrl=${{ secrets.SLACK_HOOK_URL }}"
        "-DslackStepHandlerEnabled=true"
        "-DscreenshotS3Enabled=$env:STHREE_SCREENSHOT_ENABLED"
        "-DscreenshotS3Bucket=$env:SCREENSHOT_BUCKET"
        "-DstepHandlerMessage=$env:GITHUB_SHA $env:GITHUB_ACTION"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --monochrome
        --plugin progress
        features\teamcity\teamcity-setup.feature

    - name: Add Project
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=$env:MOVE_TO_MOUSE_CUSROR"
        "-DmouseMoveVerticalOffset=$env:MOUSE_VERTICAL_OFFSET"
        "-DdisableHighlights=$env:DISABLE_HIGHLIGHTS"
        "-DdisableScreenshots=$env:DISABLE_SCREENSHOTS"
        "-DdumpAliasesOnFailure=true"
        "-DCucumberAlias-ExternalOctopusAPIKey=$((cat C:\octopus_api.txt).Trim())"
        "-DCucumberAlias-GitUrl=$env:GIT_URL"
        "-DCucumberAlias-NuGetPath=$env:NUGET_PATH"
        "-DslackHookUrl=${{ secrets.SLACK_HOOK_URL }}"
        "-DslackStepHandlerEnabled=true"
        "-DscreenshotS3Enabled=$env:STHREE_SCREENSHOT_ENABLED"
        "-DscreenshotS3Bucket=$env:SCREENSHOT_BUCKET"
        "-DstepHandlerMessage=$env:GITHUB_SHA $env:GITHUB_ACTION"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --monochrome
        --plugin progress
        --tags $env:CUCUMBER_TAGS
        features\teamcity\teamcity-aspnet-project.feature

    - name: Create the Octopus Environments
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=$env:MOVE_TO_MOUSE_CUSROR"
        "-DmouseMoveVerticalOffset=$env:MOUSE_VERTICAL_OFFSET"
        "-DdisableHighlights=$env:DISABLE_HIGHLIGHTS"
        "-DdisableScreenshots=$env:DISABLE_SCREENSHOTS"
        "-DslackHookUrl=${{ secrets.SLACK_HOOK_URL }}"
        "-DslackStepHandlerEnabled=false"
        "-DscreenshotS3Enabled=$env:STHREE_SCREENSHOT_ENABLED"
        "-DscreenshotS3Bucket=$env:SCREENSHOT_BUCKET"
        "-DstepHandlerMessage=$env:GITHUB_SHA $env:GITHUB_ACTION"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        features\octopus\octopus-environments.feature

    - name: Add tentacle
      shell: powershell
      run: '& "C:\Program Files\Puppet Labs\Puppet\bin\puppet.bat" apply puppet\windows\tentacle.pp --disable_warnings=deprecations'
    - name: Create Octopus Project
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=$env:MOVE_TO_MOUSE_CUSROR"
        "-DmouseMoveVerticalOffset=$env:MOUSE_VERTICAL_OFFSET"
        "-DdisableHighlights=$env:DISABLE_HIGHLIGHTS"
        "-DdisableScreenshots=$env:DISABLE_SCREENSHOTS"
        "-DdumpAliasesOnFailure=true"
        "-DslackHookUrl=${{ secrets.SLACK_HOOK_URL }}"
        "-DslackStepHandlerEnabled=true"
        "-DscreenshotS3Enabled=$env:STHREE_SCREENSHOT_ENABLED"
        "-DscreenshotS3Bucket=$env:SCREENSHOT_BUCKET"
        "-DstepHandlerMessage=$env:GITHUB_SHA $env:GITHUB_ACTION"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --monochrome
        --plugin progress
        --tags $env:CUCUMBER_TAGS
        features\octopus\octopus-aspnet-project.feature

    - name: Open Random Quotes
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=$env:MOVE_TO_MOUSE_CUSROR"
        "-DmouseMoveVerticalOffset=$env:MOUSE_VERTICAL_OFFSET"
        "-DdisableHighlights=$env:DISABLE_HIGHLIGHTS"
        "-DdisableScreenshots=$env:DISABLE_SCREENSHOTS"
        "-DslackHookUrl=${{ secrets.SLACK_HOOK_URL }}"
        "-DslackStepHandlerEnabled=true"
        "-DscreenshotS3Enabled=$env:STHREE_SCREENSHOT_ENABLED"
        "-DscreenshotS3Bucket=$env:SCREENSHOT_BUCKET"
        "-DstepHandlerMessage=$env:GITHUB_SHA $env:GITHUB_ACTION"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --monochrome
        --plugin progress
        features\octopus\open-randomquotes-iis-dev.feature

    - name: Add a deployment step
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=$env:MOVE_TO_MOUSE_CUSROR"
        "-DmouseMoveVerticalOffset=$env:MOUSE_VERTICAL_OFFSET"
        "-DCucumberAlias-ExternalOctopusAPIKey=$((cat C:\octopus_api.txt).Trim())"
        "-DCucumberAlias-ExternalMediaPath=$env:MEDIA_PATH"
        "-DdisableHighlights=$env:DISABLE_HIGHLIGHTS"
        "-DdisableScreenshots=$env:DISABLE_SCREENSHOTS"
        "-DslackHookUrl=${{ secrets.SLACK_HOOK_URL }}"
        "-DslackStepHandlerEnabled=false"
        "-DscreenshotS3Enabled=$env:STHREE_SCREENSHOT_ENABLED"
        "-DscreenshotS3Bucket=$env:SCREENSHOT_BUCKET"
        "-DstepHandlerMessage=$env:GITHUB_SHA $env:GITHUB_ACTION"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --monochrome
        --plugin progress
        --tags $env:CUCUMBER_TAGS
        features\teamcity\teamcity-create-deploy.feature

    - name: Add a lifecycle
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=$env:MOVE_TO_MOUSE_CUSROR"
        "-DmouseMoveVerticalOffset=$env:MOUSE_VERTICAL_OFFSET"
        "-DdisableHighlights=$env:DISABLE_HIGHLIGHTS"
        "-DdisableScreenshots=$env:DISABLE_SCREENSHOTS"
        "-DslackHookUrl=${{ secrets.SLACK_HOOK_URL }}"
        "-DslackStepHandlerEnabled=false"
        "-DscreenshotS3Enabled=$env:STHREE_SCREENSHOT_ENABLED"
        "-DscreenshotS3Bucket=$env:SCREENSHOT_BUCKET"
        "-DstepHandlerMessage=$env:GITHUB_SHA $env:GITHUB_ACTION"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --monochrome
        --plugin progress
        features\octopus\octopus-lifecycle.feature

    - name: Open Random Quotes in the test environment
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=$env:MOVE_TO_MOUSE_CUSROR"
        "-DmouseMoveVerticalOffset=$env:MOUSE_VERTICAL_OFFSET"
        "-DdisableHighlights=$env:DISABLE_HIGHLIGHTS"
        "-DdisableScreenshots=$env:DISABLE_SCREENSHOTS"
        "-DslackHookUrl=${{ secrets.SLACK_HOOK_URL }}"
        "-DslackStepHandlerEnabled=false"
        "-DscreenshotS3Enabled=$env:STHREE_SCREENSHOT_ENABLED"
        "-DscreenshotS3Bucket=$env:SCREENSHOT_BUCKET"
        "-DstepHandlerMessage=$env:GITHUB_SHA $env:GITHUB_ACTION"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --monochrome
        --plugin progress
        features\octopus\open-randomquotes-iis-test.feature

    - name: Add manual intervention
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=$env:MOVE_TO_MOUSE_CUSROR"
        "-DmouseMoveVerticalOffset=$env:MOUSE_VERTICAL_OFFSET"
        "-DdisableHighlights=$env:DISABLE_HIGHLIGHTS"
        "-DdisableScreenshots=$env:DISABLE_SCREENSHOTS"
        "-DslackHookUrl=${{ secrets.SLACK_HOOK_URL }}"
        "-DslackStepHandlerEnabled=false"
        "-DscreenshotS3Enabled=$env:STHREE_SCREENSHOT_ENABLED"
        "-DscreenshotS3Bucket=$env:SCREENSHOT_BUCKET"
        "-DstepHandlerMessage=$env:GITHUB_SHA $env:GITHUB_ACTION"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --monochrome
        --plugin progress
        features\octopus\octopus-manual-intervention.feature

    - name: Add email notification
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=$env:MOVE_TO_MOUSE_CUSROR"
        "-DmouseMoveVerticalOffset=$env:MOUSE_VERTICAL_OFFSET"
        "-DCucumberAlias-SMTPPassword=${{ secrets.GMAIL_PASSWORD }}"
        "-DdisableHighlights=$env:DISABLE_HIGHLIGHTS"
        "-DdisableScreenshots=$env:DISABLE_SCREENSHOTS"
        "-DslackHookUrl=${{ secrets.SLACK_HOOK_URL }}"
        "-DslackStepHandlerEnabled=false"
        "-DscreenshotS3Enabled=$env:STHREE_SCREENSHOT_ENABLED"
        "-DscreenshotS3Bucket=$env:SCREENSHOT_BUCKET"
        "-DstepHandlerMessage=$env:GITHUB_SHA $env:GITHUB_ACTION"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --monochrome
        --plugin progress
        features\octopus\octopus-email-notification.feature

    - name: Add users and team
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=$env:MOVE_TO_MOUSE_CUSROR"
        "-DmouseMoveVerticalOffset=$env:MOUSE_VERTICAL_OFFSET"
        "-DdisableHighlights=$env:DISABLE_HIGHLIGHTS"
        "-DdisableScreenshots=$env:DISABLE_SCREENSHOTS"
        "-DslackHookUrl=${{ secrets.SLACK_HOOK_URL }}"
        "-DslackStepHandlerEnabled=false"
        "-DscreenshotS3Enabled=$env:STHREE_SCREENSHOT_ENABLED"
        "-DscreenshotS3Bucket=$env:SCREENSHOT_BUCKET"
        "-DstepHandlerMessage=$env:GITHUB_SHA $env:GITHUB_ACTION"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --monochrome
        --plugin progress
        features\octopus\octopus-users-and-teams.feature

    - name: View internal deployer dashboard
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=$env:MOVE_TO_MOUSE_CUSROR"
        "-DmouseMoveVerticalOffset=$env:MOUSE_VERTICAL_OFFSET"
        "-DdisableHighlights=$env:DISABLE_HIGHLIGHTS"
        "-DdisableScreenshots=$env:DISABLE_SCREENSHOTS"
        "-DslackHookUrl=${{ secrets.SLACK_HOOK_URL }}"
        "-DslackStepHandlerEnabled=false"
        "-DscreenshotS3Enabled=$env:STHREE_SCREENSHOT_ENABLED"
        "-DscreenshotS3Bucket=$env:SCREENSHOT_BUCKET"
        "-DstepHandlerMessage=$env:GITHUB_SHA $env:GITHUB_ACTION"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --monochrome
        --plugin progress
        features\octopus\octopus-view-internal-deployments.feature

    - name: View production deployer dashboard
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=$env:MOVE_TO_MOUSE_CUSROR"
        "-DmouseMoveVerticalOffset=$env:MOUSE_VERTICAL_OFFSET"
        "-DdisableHighlights=$env:DISABLE_HIGHLIGHTS"
        "-DdisableScreenshots=$env:DISABLE_SCREENSHOTS"
        "-DslackHookUrl=${{ secrets.SLACK_HOOK_URL }}"
        "-DslackStepHandlerEnabled=false"
        "-DscreenshotS3Enabled=$env:STHREE_SCREENSHOT_ENABLED"
        "-DscreenshotS3Bucket=$env:SCREENSHOT_BUCKET"
        "-DstepHandlerMessage=$env:GITHUB_SHA $env:GITHUB_ACTION"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        features\octopus\octopus-view-production-deployments.feature

    - name: View audit logs
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=$env:MOVE_TO_MOUSE_CUSROR"
        "-DmouseMoveVerticalOffset=$env:MOUSE_VERTICAL_OFFSET"
        "-DdisableHighlights=$env:DISABLE_HIGHLIGHTS"
        "-DdisableScreenshots=$env:DISABLE_SCREENSHOTS"
        "-DslackHookUrl=${{ secrets.SLACK_HOOK_URL }}"
        "-DslackStepHandlerEnabled=false"
        "-DscreenshotS3Enabled=$env:STHREE_SCREENSHOT_ENABLED"
        "-DscreenshotS3Bucket=$env:SCREENSHOT_BUCKET"
        "-DstepHandlerMessage=$env:GITHUB_SHA $env:GITHUB_ACTION"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        features\octopus\octopus-audit-log.feature

    - name: Convert video
      shell: powershell
      run: gci c:\screenshots\*.avi | % {Start-Process "C:\Program Files\VideoLAN\VLC\vlc.exe" -NoNewWindow -Wait -ArgumentList @("-I", "dummy", "-vvv", "`"$($_.FullName)`"", "--sout=#transcode{vcodec=h264,vb=1024,acodec=mp4a,ab=192,channels=2,deinterlace}:standard{access=file,mux=mp4,dst=`"c:\screenshots\$($_.BaseName).mp4`"}", "vlc://quit")}
    - name: Merge video
      shell: powershell
      run: Start-Process -FilePath "C:\Program Files\VideoLAN\VLC\vlc.exe" -Wait -ArgumentList (@("-I", "dummy", "-vvv") + $(gci C:\screenshots\*.mp4 | ?{$_.Name -ne "video.mp4"} | %{"`"" + $_.FullName + "`""}) + @("--sout", "#gather:std{access=file,mux=mp4,dst=c:\screenshots\video.mp4}", "--no-sout-all", "--sout-keep", "vlc://quit"))
    - name: Speed up video
      shell: powershell
      run: Start-Process -FilePath "C:\ProgramData\chocolatey\bin\ffmpeg.exe" -Wait -ArgumentList (@("-i", "c:\screenshots\video.mp4", "-filter:v", "setpts=0.75*PTS", "c:\screenshots\fast.mp4"))
    - name: Upload video
      shell: powershell
      run: |
        ls c:\screenshots
        & "C:\Program Files\Amazon\AWSCLI\bin\aws.exe" s3 cp c:\screenshots\fast.mp4 "s3://i.octopus.com/guides/$($env:VIDEO_FILE_NAME)" --acl public-read

    - name: Replace Wistia Video
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=$env:MOVE_TO_MOUSE_CUSROR"
        "-DmouseMoveVerticalOffset=$env:MOUSE_VERTICAL_OFFSET"
        "-DdisableHighlights=$env:DISABLE_HIGHLIGHTS"
        "-DdisableScreenshots=$env:DISABLE_SCREENSHOTS"
        "-DdisableVideoRecording=true"
        "-DslackHookUrl=${{ secrets.SLACK_HOOK_URL }}"
        "-DslackStepHandlerEnabled=false"
        "-DscreenshotS3Enabled=$env:STHREE_SCREENSHOT_ENABLED"
        "-DscreenshotS3Bucket=$env:SCREENSHOT_BUCKET"
        "-DstepHandlerMessage=$env:GITHUB_SHA"
        "-DretryCount=3"
        "-DCucumberAlias-ExternalWistiaUsername=${{ secrets.WISTIA_USERNAME }}"
        "-DCucumberAlias-ExternalWistiaPassword=${{ secrets.WISTIA_PASSWORD }}"
        "-DCucumberAlias-ExternalMediaID=$env:WISTIA_MEDIA_ID"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        features\wistia\replace-video.feature
