name: ASP.NET Core Azure Devops Artifactory Feed TFVC Screenshots
on:
  #  push:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CUCUMBER_TAGS: "(not @destinationspecific or @k8s) and (not @repositoryspecific or @dockerhub) and (not @applicationspecific or @aspnetcore) and (not @sourcespecific or @git)"
      DISABLE_HIGHLIGHTS: false
      DISABLE_SCREENSHOTS: false
      MOVE_TO_MOUSE_CUSROR: false
      MOUSE_VERTICAL_OFFSET: 74
      DISABLE_VIDEO: true
      SCREENSHOT_BUCKET: octopus-guides-screenshots
      STHREE_SCREENSHOT_ENABLED: true
      GIT_URL: https://github.com/OctopusSamples/RandomQuotes.git
      NUGET_PATH:
      WISTIA_MEDIA_ID:
      VIDEO_FILE_NAME:
      SCREENSHOT_PATH: aspnetcore-app\k8s\dockerhub\git\
    steps:
      - uses: actions/checkout@v1
      - name: Install Puppet
        run: sudo apt-get install puppet-agent