name: ASP.NET Azure Devops Octopus Built-in Feed Screenshots
on: [push]
jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
    - name: Execute puppet
      shell: powershell
      run: ./install.ps1 -Scripts utilities.pp,octopus.pp,iis.pp,azuredevops.pp
    - name: Create API key
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-Dwebdriver.firefox.logfile=C:\firefox.log"
        "-DmoveCursorToElement=true"
        "-DmouseMoveVerticalOffset=74"
        "-DdisableVideoRecording=true"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --monochrome
        features\octopus\octopus-api-key.feature
    - name: Create API key for tests
      shell: powershell
      run: '& "C:\Program Files\Puppet Labs\Puppet\bin\puppet.bat" apply puppet\octopus-api-key.pp --disable_warnings=deprecations'
