name: ASP.NET Jenkins Octopus Built-in Feed Video
on:
  schedule:
    - cron:  '0 17 * * *'
jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
    - name: Execute puppet
      shell: powershell
      run: ./install.ps1 -Scripts jenkinsinstall.pp,utilities.pp,octopus.pp,iis.pp,jenkins.pp,sleep.pp,jenkinswait.pp
    - name: Create API key
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=true"
        "-DmouseMoveVerticalOffset=74"
        "-DdisableHighlights=true"
        "-DdisableScreenshots=true"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        features\octopus\octopus-api-key.feature
    - name: Create API key for tests
      shell: powershell
      run: '& "C:\Program Files\Puppet Labs\Puppet\bin\puppet.bat" apply puppet\octopus-api-key.pp --disable_warnings=deprecations'
    - name: Create Jenkins Project and Octopus
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=true"
        "-DmouseMoveVerticalOffset=74"
        "-DCucumberAlias-ExternalOctopusAPIKey=$((cat C:\octopus_api.txt).Trim())"
        "-DdisableHighlights=true"
        "-DdisableScreenshots=true"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        --tags "not @destinationspecific or @iis"
        --tags "not @repositoryspecific or @octo-built-in-feed"
        --tags "not @applicationspecific or @aspnet"
        features\jenkins\jenkins-aspnet-git.feature
    - name: Create the Octopus Environments
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=true"
        "-DmouseMoveVerticalOffset=74"
        "-DdisableHighlights=true"
        "-DdisableScreenshots=true"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        features\octopus\octopus-environments.feature
    - name: Add tentacle
      shell: powershell
      run: '& "C:\Program Files\Puppet Labs\Puppet\bin\puppet.bat" apply puppet\tentacle.pp --disable_warnings=deprecations'
    - name: Create Octopus Project
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=true"
        "-DmouseMoveVerticalOffset=74"
        "-DdisableHighlights=true"
        "-DdisableScreenshots=true"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        --tags "not @destinationspecific or @iis"
        --tags "not @repositoryspecific or @octo-built-in-feed"
        --tags "not @applicationspecific or @aspnet"
        features\octopus\octopus-aspnet-project.feature
    - name: Open Random Quotes
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=true"
        "-DmouseMoveVerticalOffset=74"
        "-DdisableHighlights=true"
        "-DdisableScreenshots=true"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        features\octopus\open-randomquotes-iis-dev.feature
    - name: Add a deployment step
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=true"
        "-DmouseMoveVerticalOffset=74"
        "-DdisableHighlights=true"
        "-DdisableScreenshots=true"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        --tags "not @destinationspecific or @iis"
        --tags "not @repositoryspecific or @octo-built-in-feed"
        --tags "not @applicationspecific or @aspnet"
        features\jenkins\jenkins-create-deploy.feature
    - name: Add a lifecycle
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=true"
        "-DmouseMoveVerticalOffset=74"
        "-DdisableHighlights=true"
        "-DdisableScreenshots=true"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        features\octopus\octopus-lifecycle.feature
    - name: Open Random Quotes in the test environment
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=true"
        "-DmouseMoveVerticalOffset=74"
        "-DdisableHighlights=true"
        "-DdisableScreenshots=true"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        features\octopus\open-randomquotes-iis-test.feature
    - name: Add manual intervention
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=true"
        "-DmouseMoveVerticalOffset=74"
        "-DdisableHighlights=true"
        "-DdisableScreenshots=true"
        "-DCucumberAlias-ApplicationURL=[http://localhost:#{IIS Port}](http://localhost:#{IIS Port})"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        features\octopus\octopus-manual-intervention.feature
    - name: Add email notification
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=true"
        "-DmouseMoveVerticalOffset=74"
        "-DCucumberAlias-SMTPPassword=${{ secrets.GMAIL_PASSWORD }}"
        "-DdisableHighlights=true"
        "-DdisableScreenshots=true"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        features\octopus\octopus-email-notification.feature
    - name: Add users and team
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=true"
        "-DmouseMoveVerticalOffset=74"
        "-DdisableHighlights=true"
        "-DdisableScreenshots=true"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        features\octopus\octopus-users-and-teams.feature
    - name: View internal deployer dashboard
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=true"
        "-DmouseMoveVerticalOffset=74"
        "-DdisableHighlights=true"
        "-DdisableScreenshots=true"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        features\octopus\octopus-view-internal-deployments.feature
    - name: View production deployer dashboard
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=true"
        "-DmouseMoveVerticalOffset=74"
        "-DdisableHighlights=true"
        "-DdisableScreenshots=true"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        features\octopus\octopus-view-production-deployments.feature
    - name: View audit logs
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=true"
        "-DmouseMoveVerticalOffset=74"
        "-DdisableHighlights=true"
        "-DdisableScreenshots=true"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        features\octopus\octopus-audit-log.feature
    - name: Convert video
      shell: powershell
      run: gci c:\screenshots\*.avi | % {Start-Process "C:\Program Files\VideoLAN\VLC\vlc.exe" -NoNewWindow -Wait -ArgumentList @("-I", "dummy", "-vvv", "`"$($_.FullName)`"", "--sout=#transcode{vcodec=h264,vb=1024,acodec=mp4a,ab=192,channels=2,deinterlace}:standard{access=file,mux=mp4,dst=`"c:\screenshots\$($_.BaseName).mp4`"}", "vlc://quit")}
    - name: Merge video
      shell: powershell
      run: Start-Process -FilePath "C:\Program Files\VideoLAN\VLC\vlc.exe" -Wait -ArgumentList (@("-I", "dummy", "-vvv") + $(gci C:\screenshots\*.mp4 | ?{$_.Name -ne "video.mp4"} | %{"`"" + $_.FullName + "`""}) + @("--sout", "#gather:std{access=file,mux=mp4,dst=c:\screenshots\video.mp4}", "--no-sout-all", "--sout-keep", "vlc://quit"))
    - name: Speed up video
      shell: powershell
      run: Start-Process -FilePath "C:\ProgramData\chocolatey\bin\ffmpeg.exe" -Wait -ArgumentList (@("-i", "c:\screenshots\video.mp4", "-filter:v", "setpts=0.75*PTS", "c:\screenshots\fast.mp4"))
    - name: Upload video
      shell: powershell
      run: |
        ls c:\screenshots
        & "C:\Program Files\Amazon\AWSCLI\bin\aws.exe" s3 cp c:\screenshots\fast.mp4 s3://i.octopus.com/guides/aspnet-jenkins-octopus-builtin-feed.mp4 --acl public-read
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}