name: ASP.NET Core Azure Devops Artifactory Feed Screenshots
on:
#  push:
  schedule:
    - cron:  '0 14 5 * *'
jobs:
  build:
    runs-on: windows-2019
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      ARTIFACTORY_KEY: ${{ secrets.ARTIFACTORY_KEY }}
      SLACK_HOOK_URL: ${{ secrets.SLACK_HOOK_URL }}
      CUCUMBER_TAGS: "(not @destinationspecific or @iis) and (not @repositoryspecific or @artifactory) and (not @applicationspecific or @aspnetcore) and (not @sourcespecific or @git)"
      WISTIA_MEDIA_ID:
      DISABLE_HIGHLIGHTS: false
      DISABLE_SCREENSHOTS: false
      MOVE_TO_MOUSE_CUSROR: false
      MOUSE_VERTICAL_OFFSET: 74
      DISABLE_VIDEO: true
      SCREENSHOT_BUCKET: octopus-guides-screenshots
      STHREE_SCREENSHOT_ENABLED: true
      GIT_URL: https://github.com/OctopusSamples/RandomQuotes.git
      NUGET_PATH: 
      VIDEO_FILE_NAME:
      SCREENSHOT_PATH: aspnetcore-app\iis\artifactory\git\
    steps:
    - uses: actions/checkout@v1
    - name: Disable Windows Defender
      shell: powershell
      run: reg add 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection' /v DisableRealtimeMonitoring /t REG_DWORD /d 1
    - name: Execute puppet
      shell: powershell
      run: ./install.ps1 -Scripts azuredevops.pp,azuredevopsagent.pp,utilities.pp,dotnetutilities.pp,artifactory.pp,octopus.pp,iis.pp,azurewait.pp,artifactorywait.pp
    - name: Configure Artifactory
      shell: powershell
      run: ./scripts/windows/configure-artifactory.ps1

    - name: Create API key
      shell: powershell
      run: ./scripts/windows/create-apikey.ps1

    - name: Create API key for tests
      shell: powershell
      run: '& "C:\Program Files\Puppet Labs\Puppet\bin\puppet.bat" apply puppet\windows\octopus-api-key.pp --disable_warnings=deprecations'
    - name: Add Azure DevOps Project
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=$env:MOVE_TO_MOUSE_CUSROR"
        "-DmouseMoveVerticalOffset=$env:MOUSE_VERTICAL_OFFSET"
        "-DdisableVideoRecording=$env:DISABLE_VIDEO"
        "-DnoProxyList=microsoft.com"
        "-DdumpAliasesOnFailure=true"
        "-DslackHookUrl=${{ secrets.SLACK_HOOK_URL }}"
        "-DslackStepHandlerEnabled=true"
        "-DscreenshotS3Enabled=$env:STHREE_SCREENSHOT_ENABLED"
        "-DscreenshotS3Bucket=$env:SCREENSHOT_BUCKET"
        "-DstepHandlerMessage=$env:GITHUB_SHA"
        "-DretryCount=1"
        "-DCucumberAlias-ExternalOctopusAPIKey=$((cat C:\octopus_api.txt).Trim())"
        "-DCucumberAlias-GitUrl=$env:GIT_URL"
        "-DCucumberAlias-NugetPath=$env:NUGET_PATH"
        "-DCucumberAlias-GuideSpecificScreenshotDir=$env:SCREENSHOT_PATH"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        --tags $env:CUCUMBER_TAGS
        features\azuredevops\azuredevops-aspnet-project.feature

    - name: Create the Octopus External Feed
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=$env:MOVE_TO_MOUSE_CUSROR"
        "-DmouseMoveVerticalOffset=$env:MOUSE_VERTICAL_OFFSET"
        "-DdisableHighlights=$env:DISABLE_HIGHLIGHTS"
        "-DdisableScreenshots=$env:DISABLE_SCREENSHOTS"
        "-DdisableVideoRecording=$env:DISABLE_VIDEO"
        "-DslackHookUrl=${{ secrets.SLACK_HOOK_URL }}"
        "-DslackStepHandlerEnabled=true"
        "-DscreenshotS3Enabled=$env:STHREE_SCREENSHOT_ENABLED"
        "-DscreenshotS3Bucket=$env:SCREENSHOT_BUCKET"
        "-DstepHandlerMessage=$env:GITHUB_SHA $env:GITHUB_ACTION"
        "-DretryCount=1"
        "-DCucumberAlias-GuideSpecificScreenshotDir=$env:SCREENSHOT_PATH"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        features\octopus\octopus-artifactory-feed.feature

    - name: Create the Octopus Environments
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=$env:MOVE_TO_MOUSE_CUSROR"
        "-DmouseMoveVerticalOffset=$env:MOUSE_VERTICAL_OFFSET"
        "-DdisableHighlights=$env:DISABLE_HIGHLIGHTS"
        "-DdisableScreenshots=$env:DISABLE_SCREENSHOTS"
        "-DdisableVideoRecording=$env:DISABLE_VIDEO"
        "-DCucumberAlias-GuideSpecificScreenshotDir=$env:SCREENSHOT_PATH"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        features\octopus\octopus-environments.feature

    - name: Add tentacle
      shell: powershell
      run: '& "C:\Program Files\Puppet Labs\Puppet\bin\puppet.bat" apply puppet\windows\tentacle.pp --disable_warnings=deprecations'
    - name: Create Octopus Project
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=$env:MOVE_TO_MOUSE_CUSROR"
        "-DmouseMoveVerticalOffset=$env:MOUSE_VERTICAL_OFFSET"
        "-DdisableVideoRecording=$env:DISABLE_VIDEO"
        "-DdisableScreenshots=$env:DISABLE_SCREENSHOTS"
        "-DCucumberAlias-GuideSpecificScreenshotDir=$env:SCREENSHOT_PATH"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        --tags $env:CUCUMBER_TAGS
        features\octopus\octopus-aspnet-project.feature

    - name: Add a deployment step
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=$env:MOVE_TO_MOUSE_CUSROR"
        "-DmouseMoveVerticalOffset=$env:MOUSE_VERTICAL_OFFSET"
        "-DdisableVideoRecording=$env:DISABLE_VIDEO"
        "-DslackHookUrl=${{ secrets.SLACK_HOOK_URL }}"
        "-DslackStepHandlerEnabled=true"
        "-DscreenshotS3Enabled=$env:STHREE_SCREENSHOT_ENABLED"
        "-DscreenshotS3Bucket=$env:SCREENSHOT_BUCKET"
        "-DstepHandlerMessage=$env:GITHUB_SHA $env:GITHUB_ACTION"
        "-DCucumberAlias-GuideSpecificScreenshotDir=$env:SCREENSHOT_PATH"
        "-DCucumberAlias-ExternalOctopusAPIKey=$((cat C:\octopus_api.txt).Trim())"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        --tags $env:CUCUMBER_TAGS
        features\azuredevops\azuredevops-create-deploy.feature

    - name: Upload screenshots
      shell: powershell
      run: |
        ls c:\screenshots
        & "C:\Program Files\Amazon\AWSCLI\bin\aws.exe" s3 sync c:\screenshots s3://i.octopus.com/guides --acl public-read

