name: ASP.NET Jenkins Octopus Built-in Feed Screenshots
on:
#  push:
  repository_disptach:
  schedule:
    - cron:  '0 20 3 * *'
jobs:
  build:
    if: (github.event_name != 'repository_dispatch') || (github.event.client_payload.workflow == github.workflow)
    runs-on: windows-2019
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      WISTIA_USERNAME: ${{ secrets.WISTIA_USERNAME }}
      WISTIA_PASSWORD: ${{ secrets.WISTIA_PASSWORD }}
      SLACK_HOOK_URL: ${{ secrets.SLACK_HOOK_URL }}
      MEDIA_PATH: C:\screenshots
      CUCUMBER_TAGS: "(not @destinationspecific or @iis) and (not @repositoryspecific or @octo-built-in-feed) and (not @applicationspecific or @aspnet) and (not @sourcespecific or @git)"
      WISTIA_MEDIA_ID:
      DISABLE_HIGHLIGHTS: false
      DISABLE_SCREENSHOTS: false
      MOVE_TO_MOUSE_CUSROR: false
      DISABLE_VIDEO: true
      MOUSE_VERTICAL_OFFSET: 74
      SCREENSHOT_BUCKET: octopus-guides-screenshots
      STHREE_SCREENSHOT_ENABLED: true
      GIT_URL: https://github.com/OctopusSamples/RandomQuotes-aspmvc4.git
      NUGET_PATH: 'RandomQuotes\obj\octopacked\'
      VIDEO_FILE_NAME:
      SCREENSHOT_PATH: aspnet-app\iis\builtin\git\
    steps:
    - uses: actions/checkout@v1

    - name: Set screen resolution
      shell: powershell
      run: ./scripts/windows/set-resolution.ps1

    - name: Disable Windows Defender
      shell: powershell
      run: reg add 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection' /v DisableRealtimeMonitoring /t REG_DWORD /d 1

    - name: Execute puppet
      shell: powershell
      run: ./install.ps1 -Scripts jenkinsinstall.pp,utilities.pp,dotnetutilities.pp,octopus.pp,iis.pp,jenkins.pp,sleep.pp,jenkinswait.pp

    - name: Create API key
      shell: powershell
      run: ./scripts/windows/create-apikey.ps1

    - name: Create API key for tests
      shell: powershell
      run: '& "C:\Program Files\Puppet Labs\Puppet\bin\puppet.bat" apply puppet\windows\octopus-api-key.pp --disable_warnings=deprecations'

    - name: Create Jenkins Project
      shell: powershell
      run: ./scripts/windows/jenkins-create-project.ps1

    - name: Create the Octopus Environments
      shell: powershell
      run: ./scripts/windows/create-environments.ps1

    - name: Add tentacle
      shell: powershell
      run: '& "C:\Program Files\Puppet Labs\Puppet\bin\puppet.bat" apply puppet\windows\tentacle.pp --disable_warnings=deprecations'

    - name: Create Octopus Project
      shell: powershell
      run: ./scripts/windows/create-octopusaspnetproject.ps1

    - name: Open Random Quotes
      shell: powershell
      run: ./scripts/windows/open-iisdevapp.ps1

    - name: Add a deployment step
      shell: powershell
      run: ./scripts/windows/jenkins-create-deployment.ps1

    - name: Add a lifecycle
      shell: powershell
      run: ./scripts/windows/create-lifecycle.ps1

    - name: Open Random Quotes in the test environment
      shell: powershell
      run: ./scripts/windows/open-iistestapp.ps1

    - name: Add manual intervention
      shell: powershell
      run: ./scripts/windows/add-manualintervention.ps1

    - name: Add email notification
      shell: powershell
      run: ./scripts/windows/add-notification.ps1

    - name: Add users and team
      shell: powershell
      run: ./scripts/windows/create-usersandteams.ps1

    - name: View internal deployer dashboard
      shell: powershell
      run: ./scripts/windows/view-internaldeployerdashboard.ps1

    - name: View production deployer dashboard
      shell: powershell
      run: ./scripts/windows/view-productiondeployerdashboard.ps1

    - name: View audit logs
      shell: powershell
      run: ./scripts/windows/view-auditlogs.ps1

    - name: Upload screenshots
      shell: powershell
      run: ./scripts/windows/upload-screenshots.ps1
