name: ASP.NET Core Azure Devops Kubernetes DockerHub Video
on:
    push:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CUCUMBER_TAGS: "(not @destinationspecific or @k8s) and (not @repositoryspecific or @dockerhub) and (not @applicationspecific or @aspnetcore) and (not @sourcespecific or @git)"
      DISABLE_HIGHLIGHTS: true
      DISABLE_SCREENSHOTS: true
      MOVE_TO_MOUSE_CURSOR: true
      MOUSE_VERTICAL_OFFSET: 74
      DISABLE_VIDEO: false
      STHREE_SCREENSHOT_ENABLED: true
      SCREENSHOT_BUCKET: octopus-guides-screenshots
      GIT_URL: https://github.com/OctopusSamples/RandomQuotes.git
      WISTIA_MEDIA_ID:
      VIDEO_FILE_NAME: aspnetcore-k8s-dockerhub.mp4
      SCREENSHOT_PATH: aspnetcore-app\k8s\dockerhub\git\
    steps:
      - uses: actions/checkout@v1
      - name: Install Puppet
        run: ./install.sh minikube.pp dockercreds.pp dotnetutilities.pp octopus.pp utilities.pp
        env:
          FACTER_dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
          FACTER_dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Create certificates
        run: >
          /usr/lib/jvm/java-13-openjdk-amd64/bin/java
          "--enable-preview"
          "-Xmx2g"
          "-Dwebdriver.gecko.driver=/usr/bin/geckodriver"
          "-DmoveCursorToElement=$MOVE_TO_MOUSE_CURSOR"
          "-DmouseMoveVerticalOffset=$MOUSE_VERTICAL_OFFSET"
          "-DdisableHighlights=$DISABLE_HIGHLIGHTS"
          "-DdisableScreenshots=$DISABLE_SCREENSHOTS"
          "-DslackHookUrl=${{ secrets.SLACK_HOOK_URL }}"
          "-DscreenshotS3Enabled=$STHREE_SCREENSHOT_ENABLED"
          "-DscreenshotS3Bucket=$SCREENSHOT_BUCKET"
          "-DstepHandlerMessage=$GITHUB_SHA"
          "-DslackStepHandlerEnabled=true"
          -jar /opt/webdrivertraining-1.0-SNAPSHOT.jar
          --plugin progress
          --monochrome
          features/octopus/octopus-create-certificate.feature
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          DISPLAY: ":99.0"