name: ASP.NET Jenkins Octopus Built-in Feed Azure Websites Video
on:
#  push:
  schedule:
    - cron:  '0 19 3 * *'
jobs:
  build:
    runs-on: windows-2019
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      WISTIA_USERNAME: ${{ secrets.WISTIA_USERNAME }}
      WISTIA_PASSWORD: ${{ secrets.WISTIA_PASSWORD }}
      SLACK_HOOK_URL: ${{ secrets.SLACK_HOOK_URL }}
      CUCUMBER_TAGS: "(not @destinationspecific or @azure-web-app) and (not @repositoryspecific or @octo-built-in-feed) and (not @applicationspecific or @aspnet) and (not @sourcespecific or @git)"
      WISTIA_MEDIA_ID: xgn6egark8
      VIDEO_FILE_NAME: aspnet-jenkins-octopus-builtin-feed-azure.mp4
      DISABLE_HIGHLIGHTS: true
      DISABLE_SCREENSHOTS: true
      MOVE_TO_MOUSE_CUSROR: true
      MOUSE_VERTICAL_OFFSET: 74
      SCREENSHOT_BUCKET: octopus-guides-screenshots
      STHREE_SCREENSHOT_ENABLED: true
      GIT_URL: https://github.com/OctopusSamples/RandomQuotes-aspmvc4.git
      NUGET_PATH: 'RandomQuotes\obj\octopacked\'
      SCREENSHOT_PATH: aspnet-app\azurewebapp\builtin\git\
    steps:
    - uses: actions/checkout@v1
    - name: Disable Windows Defender
      shell: powershell
      run: reg add 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection' /v DisableRealtimeMonitoring /t REG_DWORD /d 1
    - uses: azure/actions/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Create Web App
      shell: powershell
      run: |
        ./create-azure-web-app "jenkinsaspnetbuiltinfeedviddev"
        ./create-azure-web-app "jenkinsaspnetbuiltinfeedvidtest"
        ./create-azure-web-app "jenkinsaspnetbuiltinfeedvidprod"
    - name: Execute puppet
      shell: powershell
      run: ./install.ps1 -Scripts jenkinsinstall.pp,utilities.pp,dotnetutilities.pp,octopus.pp,iis.pp,jenkins.pp,sleep.pp,jenkinswait.pp
    - name: Create API key
      shell: powershell
      run: ./scripts/windows/create-apikey.ps1

    - name: Create API key for tests
      shell: powershell
      run: '& "C:\Program Files\Puppet Labs\Puppet\bin\puppet.bat" apply puppet\windows\octopus-api-key.pp --disable_warnings=deprecations'
    - name: Create Jenkins Project and Octopus
      shell: powershell
      run: ./scripts/windows/jenkins-create-project.ps1

    - name: Create the Octopus Environments
      shell: powershell
      run: ./scripts/windows/create-environments.ps1

    - name: Create the Octopus Azure Account
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=true"
        "-DmouseMoveVerticalOffset=74"
        "-DdisableVideoRecording=false"
        "-DdisableScreenshots=true"
        "-DdisableHighlights=true"
        "-DdisableBrowserZoom=true"
        "-DslackHookUrl=${{ secrets.SLACK_HOOK_URL }}"
        "-DslackStepHandlerEnabled=true"
        "-DscreenshotS3Enabled=true"
        "-DscreenshotS3Bucket=octopus-guides-screenshots"
        "-DstepHandlerMessage=$env:GITHUB_SHA $env:GITHUB_ACTION"
        "-DCucumberAlias-ExternalArtifactoryKey=${{ secrets.ARTIFACTORY_KEY }}"
        "-DCucumberAlias-ExternalApplicationPassword=${{ secrets.ExternalApplicationPassword }}"
        "-DCucumberAlias-ExternalApplicationTenantID=${{ secrets.ExternalApplicationTenantID }}"
        "-DCucumberAlias-ExternalAzureTenantID=${{ secrets.ExternalAzureTenantID }}"
        "-DCucumberAlias-ExternalAzureSubscriptionID=${{ secrets.ExternalAzureSubscriptionID }}"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        features\octopus\octopus-create-azure-account.feature

    - name: Create Dev Azure target
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=true"
        "-DmouseMoveVerticalOffset=74"
        "-DdisableVideoRecording=false"
        "-DdisableScreenshots=true"
        "-DdisableHighlights=true"
        "-DslackHookUrl=${{ secrets.SLACK_HOOK_URL }}"
        "-DslackStepHandlerEnabled=true"
        "-DscreenshotS3Enabled=true"
        "-DscreenshotS3Bucket=octopus-guides-screenshots"
        "-DstepHandlerMessage=$env:GITHUB_SHA $env:GITHUB_ACTION"
        "-DCucumberAlias-ExternalArtifactoryKey=${{ secrets.ARTIFACTORY_KEY }}"
        "-DCucumberAlias-ExternalEnvironmentName=Dev"
        "-DCucumberAlias-ExternalTargetName=Azure web app - Dev"
        "-DCucumberAlias-ExternalEnvironment=//span[./div/div/div[text()='Dev']]"
        "-DCucumberAlias-ExternalAzureWebAppOption=//span[./div/div/div[contains(.,'jenkinsaspnetbuiltinfeedviddev')]]"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        features\octopus\octopus-create-azure-webapp-target.feature

    - name: Create Test Azure target
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=true"
        "-DmouseMoveVerticalOffset=74"
        "-DdisableVideoRecording=false"
        "-DdisableScreenshots=true"
        "-DdisableHighlights=true"
        "-DslackHookUrl=${{ secrets.SLACK_HOOK_URL }}"
        "-DslackStepHandlerEnabled=true"
        "-DscreenshotS3Enabled=true"
        "-DscreenshotS3Bucket=octopus-guides-screenshots"
        "-DstepHandlerMessage=$env:GITHUB_SHA $env:GITHUB_ACTION"
        "-DCucumberAlias-ExternalArtifactoryKey=${{ secrets.ARTIFACTORY_KEY }}"
        "-DCucumberAlias-ExternalApplicationPassword=${{ secrets.ExternalApplicationPassword }}"
        "-DCucumberAlias-ExternalApplicationTenantID=${{ secrets.ExternalApplicationTenantID }}"
        "-DCucumberAlias-ExternalAzureTenantID=${{ secrets.ExternalAzureTenantID }}"
        "-DCucumberAlias-ExternalAzureSubscriptionID=${{ secrets.ExternalAzureSubscriptionID }}"
        "-DCucumberAlias-ExternalEnvironmentName=Test"
        "-DCucumberAlias-ExternalTargetName=Azure web app - Test"
        "-DCucumberAlias-ExternalEnvironment=//span[./div/div/div[text()='Test']]"
        "-DCucumberAlias-ExternalAzureWebAppOption=//span[./div/div/div[contains(.,'jenkinsaspnetbuiltinfeedvidtest')]]"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        features\octopus\octopus-create-azure-webapp-target.feature

    - name: Create Prod Azure target
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=true"
        "-DmouseMoveVerticalOffset=74"
        "-DdisableVideoRecording=false"
        "-DdisableScreenshots=true"
        "-DdisableHighlights=true"
        "-DslackHookUrl=${{ secrets.SLACK_HOOK_URL }}"
        "-DslackStepHandlerEnabled=true"
        "-DscreenshotS3Enabled=true"
        "-DscreenshotS3Bucket=octopus-guides-screenshots"
        "-DstepHandlerMessage=$env:GITHUB_SHA $env:GITHUB_ACTION"
        "-DCucumberAlias-ExternalArtifactoryKey=${{ secrets.ARTIFACTORY_KEY }}"
        "-DCucumberAlias-ExternalApplicationPassword=${{ secrets.ExternalApplicationPassword }}"
        "-DCucumberAlias-ExternalApplicationTenantID=${{ secrets.ExternalApplicationTenantID }}"
        "-DCucumberAlias-ExternalAzureTenantID=${{ secrets.ExternalAzureTenantID }}"
        "-DCucumberAlias-ExternalAzureSubscriptionID=${{ secrets.ExternalAzureSubscriptionID }}"
        "-DCucumberAlias-ExternalEnvironmentName=Prod"
        "-DCucumberAlias-ExternalTargetName=Azure web app - Prod"
        "-DCucumberAlias-ExternalEnvironment=//span[./div/div/div[text()='Prod']]"
        "-DCucumberAlias-ExternalAzureWebAppOption=//span[./div/div/div[contains(.,'jenkinsaspnetbuiltinfeedvidprod')]]"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        features\octopus\octopus-create-azure-webapp-target.feature

    - name: Create Octopus Project
      shell: powershell
      run: ./scripts/windows/create-octopusaspnetproject.ps1
    - name: Open Random Quotes
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=true"
        "-DmouseMoveVerticalOffset=74"
        "-DdisableVideoRecording=false"
        "-DdisableScreenshots=true"
        "-DdisableHighlights=true"
        "-DCucumberAlias-ExternalUrl=https://jenkinsaspnetbuiltinfeedviddev.azurewebsites.net/"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        features\octopus\open-randomquotes-azurewebapp.feature

    - name: Add a deployment step
      shell: powershell
      run: ./scripts/windows/jenkins-create-deployment.ps1

    - name: Add a lifecycle
      shell: powershell
      run: ./scripts/windows/create-lifecycle.ps1

    - name: Open Random Quotes
      shell: powershell
      run: >
        & "C:\Program Files\OpenJDK\jdk-13\bin\java"
        "--enable-preview"
        "-Xmx2g"
        "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
        "-DmoveCursorToElement=true"
        "-DmouseMoveVerticalOffset=74"
        "-DdisableVideoRecording=false"
        "-DdisableScreenshots=true"
        "-DdisableHighlights=true"
        "-DCucumberAlias-ExternalUrl=https://jenkinsaspnetbuiltinfeedvidtest.azurewebsites.net/"
        -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
        --plugin progress
        --monochrome
        features\octopus\open-randomquotes-azurewebapp.feature

    - name: Add manual intervention
      shell: powershell
      run: ./scripts/windows/add-manualintervention.ps1

    - name: Add email notification
      shell: powershell
      run: ./scripts/windows/add-notification.ps1

    - name: Add users and team
      shell: powershell
      run: ./scripts/windows/create-usersandteams.ps1

    - name: View internal deployer dashboard
      shell: powershell
      run: ./scripts/windows/view-internaldeployerdashboard.ps1

    - name: View production deployer dashboard
      shell: powershell
      run: ./scripts/windows/view-productiondeployerdashboard.ps1

    - name: View audit logs
      shell: powershell
      run: ./scripts/windows/view-auditlogs.ps1

    - name: Process video
      shell: powershell
      run: ./scripts/windows/process-video.ps1
    - name: Upload video
      shell: powershell
      run: ./scripts/windows/upload-video.ps1
    - name: Replace Wistia Video
      shell: powershell
      run: ./scripts/windows/replace-wistia-video.ps1

    - name: Delete resource groups
      shell: powershell
      run: |
        ./delete-resource-group.ps1 "jenkinsaspnetbuiltinfeedviddev"
        ./delete-resource-group.ps1 "jenkinsaspnetbuiltinfeedvidtest"
        ./delete-resource-group.ps1 "jenkinsaspnetbuiltinfeedvidprod"