name: ASP.NET Jenkins Octopus Built-in Feed Azure WebSites Screenshots
#on: [push]
on:
  schedule:
    - cron:  '0 17 * * *'
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - uses: azure/actions/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Create Web App
        shell: powershell
        run: |
          $name = "jenkinsaspnetbuiltinfeeddev"
          $exists = & az group exists --name $name
          if ($exists -eq "false") {
            az group create --location australiaeast --name $name --tags Lifetime=Permanent OwnerContact=@matthew.casperson
          }
          $plans = & az appservice plan list --resource-group $name | ConvertFrom-Json
          if ($plans.Count -eq 0) {
            az appservice plan create --name $name --resource-group $name --number-of-workers 1 --sku F1
          }
          $apps = az webapp list --resource-group $name | ConvertFrom-Json
          if ($apps.Count -eq 0) {
            az webapp create -g $name -p $name -n $name --% --runtime "aspnet|V4.7"
            az webapp log config -g $name -n $name --application-logging true --detailed-error-messages true --web-server-logging filesystem
          }
      - name: Execute puppet
        shell: powershell
        run: ./install.ps1 -Scripts jenkinsinstall.pp,utilities.pp,octopus.pp,iis.pp,jenkins.pp,jenkinswait.pp
      - name: Create API key
        shell: powershell
        run: >
          & "C:\Program Files\OpenJDK\jdk-13\bin\java"
          "--enable-preview"
          "-Xmx2g"
          "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
          "-Dwebdriver.firefox.logfile=C:\firefox.log"
          "-DmoveCursorToElement=true"
          "-DmouseMoveVerticalOffset=74"
          "-DdisableVideoRecording=true"
          "-DslackHookUrl=${{ secrets.SLACK_HOOK_URL }}"
          "-DCucumberAlias-ExternalArtifactoryKey=${{ secrets.ARTIFACTORY_KEY }}"
          "-DslackStepHandlerEnabled=false"
          "-DscreenshotS3Enabled=true"
          "-DscreenshotS3Bucket=octopus-guides-screenshots"
          "-DstepHandlerMessage=$env:GITHUB_SHA $env:GITHUB_ACTION"
          -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
          --monochrome
          features\octopus\octopus-api-key.feature
      - name: Create the Octopus Environments
        shell: powershell
        run: >
          & "C:\Program Files\OpenJDK\jdk-13\bin\java"
          "--enable-preview"
          "-Xmx2g"
          "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
          "-Dwebdriver.firefox.logfile=C:\firefox.log"
          "-DmoveCursorToElement=true"
          "-DmouseMoveVerticalOffset=74"
          "-DdisableVideoRecording=true"
          "-DslackHookUrl=${{ secrets.SLACK_HOOK_URL }}"
          "-DCucumberAlias-ExternalArtifactoryKey=${{ secrets.ARTIFACTORY_KEY }}"
          "-DslackStepHandlerEnabled=true"
          "-DscreenshotS3Enabled=true"
          "-DscreenshotS3Bucket=octopus-guides-screenshots"
          "-DstepHandlerMessage=$env:GITHUB_SHA $env:GITHUB_ACTION"
          -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
          --monochrome
          features\octopus\octopus-environments.feature
      - name: Create the Octopus Azure Account
        shell: powershell
        run: >
          & "C:\Program Files\OpenJDK\jdk-13\bin\java"
          "--enable-preview"
          "-Xmx2g"
          "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
          "-Dwebdriver.firefox.logfile=C:\firefox.log"
          "-DmoveCursorToElement=true"
          "-DmouseMoveVerticalOffset=74"
          "-DdisableVideoRecording=true"
          "-DslackHookUrl=${{ secrets.SLACK_HOOK_URL }}"
          "-DCucumberAlias-ExternalArtifactoryKey=${{ secrets.ARTIFACTORY_KEY }}"
          "-DslackStepHandlerEnabled=true"
          "-DscreenshotS3Enabled=true"
          "-DscreenshotS3Bucket=octopus-guides-screenshots"
          "-DstepHandlerMessage=$env:GITHUB_SHA $env:GITHUB_ACTION"
          -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
          --monochrome
          features\octopus\octopus-create-azure-account.feature
      - name: Create Azure target
        shell: powershell
        run: >
          & "C:\Program Files\OpenJDK\jdk-13\bin\java"
          "--enable-preview"
          "-Xmx2g"
          "-Dwebdriver.gecko.driver=C:\tools\geckodriver.exe"
          "-Dwebdriver.firefox.logfile=C:\firefox.log"
          "-DmoveCursorToElement=true"
          "-DmouseMoveVerticalOffset=74"
          "-DdisableVideoRecording=true"
          "-DslackHookUrl=${{ secrets.SLACK_HOOK_URL }}"
          "-DCucumberAlias-ExternalArtifactoryKey=${{ secrets.ARTIFACTORY_KEY }}"
          "-DslackStepHandlerEnabled=true"
          "-DscreenshotS3Enabled=true"
          "-DscreenshotS3Bucket=octopus-guides-screenshots"
          "-DstepHandlerMessage=$env:GITHUB_SHA $env:GITHUB_ACTION"
          "-DCucumberAlias-ExternalApplicationPassword=${{ secrets.ExternalApplicationPassword }}"
          "-DCucumberAlias-ExternalApplicationTenantID=${{ secrets.ExternalApplicationTenantID }}"
          "-DCucumberAlias-ExternalAzureTenantID=${{ secrets.ExternalAzureTenantID }}"
          "-DCucumberAlias-ExternalAzureSubscriptionID=${{ secrets.ExternalAzureSubscriptionID }}"
          -jar c:\tools\webdrivertraining-1.0-SNAPSHOT.jar
          --monochrome
          features\octopus\octopus-create-azure-webapp-target.feature
#      - name: Delete resource group
#        shell: powershell
#        run: |
#          $name = "jenkinsaspnetbuiltinfeeddev"
#          $exists = & az group exists --name $name
#          if ($exists -eq "true") {
#            az group delete --name $name --yes
#          }