name: Java Jenkins Wildfly Builtin Feed Screenshots
on:
  push:
  repository_dispatch:
  schedule:
    - cron:  '0 0 22 * *'
jobs:
  build:
    if: >-
      (github.event_name != 'repository_dispatch') ||
      (github.event.client_payload.workflow == github.workflow) ||
      (github.event.client_payload.workflow == 'all') ||
      (github.event.client_payload.workflow == 'jenkins-javawar-wildfly-screenshots')
    runs-on: ubuntu-latest
    env:
      SLACK_STEP_HANDLER: true
      SLACK_ON_ERROR_ONLY: true
      STEP_PAUSE: 1000
      SLACK_HOOK_URL: ${{ secrets.SLACK_PRIVATE_HOOK_URL_1 }}
      SMTP_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      WISTIA_USERNAME: ${{ secrets.WISTIA_USERNAME }}
      WISTIA_PASSWORD: ${{ secrets.WISTIA_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      MEDIA_PATH: /tmp/screenshots
      SCREENSHOT_BUCKET: octopus-guides-screenshots
      DISPLAY: ":99.0"
      BROWSER_TYPE: FirefoxNoImplicitWait
      CUCUMBER_PLUGIN: progress
      MOUSE_VERTICAL_OFFSET: 74
      MOUSE_VERTICAL_OFFSET_CHROME: 125
      CUCUMBER_TAGS: >-
        (not @browserspecific or @firefox) and
        (not @destinationspecific or @wildfly) and
        (not @repositoryspecific or @octo-built-in-feed) and
        (not @applicationspecific or @java) and
        (not @sourcespecific or @git)
      DISABLE_HIGHLIGHTS: false
      DISABLE_SCREENSHOTS: false
      MOVE_TO_MOUSE_CURSOR: false
      DISABLE_VIDEO: true
      STHREE_SCREENSHOT_ENABLED: true
      GIT_URL: https://github.com/OctopusSamples/RandomQuotes-Java.git
      SCREENSHOT_PATH: /java-app/tomcat/builtin/git/
      DOCKER_IMAGE: octopusdeploy/randomquotesjava
      OCTOPUS_DOCKER_IMAGE: octopusdeploy/randomquotesjava
      CREATE_RELEASE_SHELL_LOCATOR: "(//div[@class='CodeMirror'])[2]"
    steps:
      - uses: actions/checkout@v1

      - name: Install Puppet
        run: ./install.sh utilities.pp headless.pp jenkins.pp wildfly.pp octopus.pp octopuscli.pp jenkinsfinalize.pp


      - name: Wait for Octopus
        run: ./scripts/linux/wait-octopus.sh

      - name: Create Api Key
        run: ./scripts/linux/create-apikey.sh

      - name: Create Jenkins project
        run: ./scripts/linux/create-javawar-jenkinsproject.sh

      - name: Create environments
        run: ./scripts/linux/create-environments.sh

      - name: Create Target
        run: sudo ./scripts/linux/create-target.sh

      - name: Create project
        run: ./scripts/linux/create-wildflyproject.sh

      - name: Open Tomcat Manager
        run: ./scripts/linux/view-tomcatmanager.sh

      - name: Open Dev App
        run: ./scripts/linux/open-wildflydevwebapp.sh

      - name: Create release
        run: ./scripts/linux/create-jenkinscreaterelease.sh

      - name: Create Lifecycle
        run: ./scripts/linux/create-lifecycle.sh

      - name: Open Test App
        run: ./scripts/linux/open-wildflytestwebapp.sh

      - name: Add Manual Intervention
        run: ./scripts/linux/add-manualintervention.sh

      - name: Add Notification
        run: ./scripts/linux/add-notification.sh

      - name: Add Users and Teams
        run: ./scripts/linux/add-usersandteams.sh

      - name: View Internal Deployer Dashboard
        run: ./scripts/linux/view-internaldeployerdashboard.sh

      - name: View Production Deployer Dashboard
        run: ./scripts/linux/view-productiondeployerdashboard.sh

      - name: View Audit Logs
        run: ./scripts/linux/view-auditlogs.sh

      - name: Upload screenshots
        run: ./scripts/linux/upload-screenshots.sh