name: CI
on: [push]
jobs:
  build:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@v1
    - name: Prepare Puppet
      run: powershell ./prepare.ps1
    - name: Run a one-line script
      run: "C:\Program Files\Puppet Labs\Puppet\bin\puppet.bat" apply octopus.pp --disable_warnings=deprecations