name: Test Workflow
on: [push]
jobs:
  build:
    if: (github.event_name != 'repository_dispatch') || (github.event.client_payload.workflow == github.workflow) || (github.event.client_payload.workflow == 'all')
    runs-on: ubuntu-latest
    steps:
    - name: Download WebDriver
      run: cd ~; pwd