name: Test Workflow
on: [push]
jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Download WebDriver
      shell: powershell
      run: mkdir c:\sysinternals; cd c:\sysinternals; Invoke-WebRequest -Uri https://download.sysinternals.com/files/SysinternalsSuite.zip -OutFile SysinternalsSuite.zip; Expand-Archive -LiteralPath SysinternalsSuite.zip -DestinationPath c:\sysinternals; ./du c:\